### ISSUE TITLE
Templating error

### ISSUE THREAD

**Issue by anneschuth** [soudy/epp#3]
I just installed `epp` using 
```bash
go get github.com/blendle/epp
```

When running the following in my terminal
```bash
echo "{{ A }}" > foo.bar
export A=B
epp foo.bar
```
I get this unexpected error:
```
templating error: template: test:1: function "A" not defined
```

**Comment by JeanMertz** [comment]
Yes, this is confusing.

This is @soudy's epp, which uses `{{ HELLO_WORLD }}`. We have a fork at https://github.com/blendle/epp, which uses `{{ env "HELLO_WORLD" }}`.

See https://github.com/blendle/epp/releases/tag/v2.0.0-rc1

Even more confusing (for backward compatibility reasons), is that the templating in `config/deploy/resources/*.yml` uses the `{{ HELLO_WORLD }}` syntax, while `config/deploy/charts.yml` uses `{{ env "HELLO_WORLD" }`.

I hope to straighten this out soon.

**Comment by anneschuth** [comment]
Ok! That's confusing indeed. I didn't even realize I ended up here instead of https://github.com/blendle/epp. A bit of documentation in the README would already have helped me.

**Comment by JeanMertz** [comment]
Agreed. I clarified this a bit here:

https://github.com/blendle/epp/blob/master/README.md#note-about-two-epp-versions

**Comment by soudy** [comment]
@JeanMertz I've added a deprecation message to the readme, if you would like me to remove this repo just shoot me a message :smile:
